#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# This script links the sources into the directory tree in parallel to the package.

# Input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer

# Link sources into the package tree

  package_tree="scratchpad/com/ReasoningTechnology/$PROJECT"
  mkdir -p "$package_tree"
  echo "Package: $package_tree"

  echo -n "Linking:"
  for source_file in javac🖉/*.java; do
    echo -n " $(basename "$source_file")"
    link_target="$package_tree/$(basename "$source_file")"
    if [ ! -L "$link_target" ]; then
      ln -s "$(realpath --relative-to="$package_tree" "$source_file")" "$link_target"
    fi
  done
  echo "."

echo "$(script_fp) done."
