#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# This script expands Mosaic third party projects onto the scratchpad. This is done before releasing or running local ad hoc tests, so that the third party tools will be present.  I.e. this is for creating a 'fat' jar.

# Input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer

# Expand the third party tools into the package tree

  echo "Expanding .jar files to be included with Mosaic into scratchpad."

  third_party_jars=(
    "$LOGGER_FACADE"
    "$LOGGER_CLASSIC"
    "$LOGGER_CORE"
  )

  pushd scratchpad >& /dev/null
  
  for jar in "${third_party_jars[@]}"; do
    if [ -f "$jar" ]; then
      echo "including $jar"
      jar -xf "$jar"
    else
      echo "Warning: JAR file not found: $jar"
    fi
  done

  # we are not currently using modules
  rm -rf module-info.class



echo "$(script_fp) done."
