#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer

echo "Compiling files..."
  set -x
  javac -Xlint:deprecation -g -d scratchpad javac🖉/*.java
  set +x
  if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
  fi

echo "Creating bash wrappers..."
  mkdir -p bash
  # wrapper is a space separated list
  wrapper=$(bash_wrapper_list)
  for file in $wrapper;do
    cat > bash/$file << EOL
#!/bin/bash
java com.ReasoningTechnology."$PROJECT".$file
EOL
    chmod +x bash/$file
  done

echo "$(script_fp) done."

