#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  if [ -z "$REPO_HOME" ]; then
    echo "$(script_fp):: REPO_HOME is not set."
    exit 1
  fi

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# script local environment

  release_dir="$REPO_HOME/release"
  bash_dir="$REPO_HOME/developer/bash"
  project_jar_fp="$REPO_HOME/developer/jvm/"$PROJECT".jar"
  wrapper=$(bash_wrapper_list)


  if [ ! -d "$release_dir" ]; then
    mkdir -p "$release_dir"
  fi

  # Function to copy and set permissions
  install_file() {
    source_fp="$1"
    target_dp="$2"
    perms="$3"

    target_file="$target_dp/$(basename "$source_fp")"

    if [ ! -f "$source_fp" ]; then
      echo "install_file:: Source file '$source_fp' does not exist."
      return 1
    fi

    if ! install -m "$perms" "$source_fp" "$target_file"; then
      echo "Error: Failed to install $(basename "$source_fp") to $target_dp"
      exit 1
    else
      echo "Installed $(basename "$source_fp") to $target_dp with permissions $perms"
    fi
  }
 
# do the release

  echo "Starting release process..."

  # Install the JAR file
  install_file "$project_jar_fp" "$release_dir" "ug+r"

  # Install bash wrappers
  for wrapper in $wrapper; do
    install_file "$bash_dir/$wrapper" "$release_dir" "ug+r+x"
  done

echo "$(script_fp) done."
