#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer

# list of classes that have main calls and get shell wrappers
echo Mosaic
