#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# each test listed here will receive a shell wrapper, and run_tests will
# include the test in the test run, in the order it appears in the list.

# input guards
env_must_be="tester/tool🖉/env"
if [ "$ENV" != "$env_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $env_must_be environment"
  exit 1
fi

# space separated list of bash interface wrappers
echo\
  Test_Logger\
  Test0\
  Test_Util\
  Test_IO\
  Test_Testbench\
  Test_MockClass_0\
  Test_Util_proxy\
  Test_IsPrimitive\
  Test_FunctionSignature\
  ""
