#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# Caveat: the 'shell' directory is for built wrapper
# functions. `clean_build_directories` will remove all the files in this
# directory. For bespoke scripts used by the tester, put them in the `tool`
# directory.

# input guards
  env_must_be="tester/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# remove files
  set -x
  cd "$REPO_HOME"/tester
  rm_na -r scratchpad/*
  rm_na jvm/*
  rm_na bash/*
  set +x

echo "$(script_fn) done."
