#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards
  env_must_be="tester/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# remove files
  set -x
  cd "$REPO_HOME"/tester
  rm_na log/log.txt
  rm_na -r scratchpad/*
  rm_na jvm/*
  rm_na jdwp_server/*
  set +x

echo "$(script_fn) done."
