#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# returns list of tests to be used by 'make' and for 'run'

# input guards
env_must_be="tester/tool🖉/env"
if [ "$ENV" != "$env_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $env_must_be environment"
  exit 1
fi

# the list

echo\
  smoke\
  Logger\
  Util\
  IO\
  Testbench\
  MockClass_0\
  IsPrimitive\
  Dispatcher_0\
  Dispatcher_1\
  Dispatcher_2\
""

#  Dispatch_1\
