#!/bin/env bash
set -x
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

env_must_be="tester/tool🖉/env"
if [ "$ENV" != "$env_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $env_must_be environment"
  exit 1
fi

echo "Compiling files..."

set -x
cd $REPO_HOME/tester

# Get the list of tests to compile
# wrapper is a space-separated list
list=$(list)

# make class files
for file in $list; do
  javac -g -d scratchpad "javac🖉/$file.java"
done
set +x 

echo "Making jvm scripts ..."
mkdir -p jvm
for file in $list; do
  cat > jvm/$file << EOL
#!/bin/env bash
java $file
EOL
  chmod +x jvm/$file
  done

echo "Making jdwp debug server scripts..."
mkdir -p jdwp_server
for file in $list; do
  cat > jdwp_server/$file << EOL
#!/bin/env bash
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 $file
EOL
  chmod +x jdwp_server/$file
  done

echo "$(script_fp) done."



set +x
