#!/usr/bin/bash

# This is the base environment shared by all roles in the project.

# The project administrator sets up the following tools for all roles to use:
#
export JAVA_HOME="$REPO_HOME/tool_shared/third_party/jdk-11"

# Absolute path to script directory, for local use in other functions, but the use
# of eval makes it suitable for exporting and use with other scripts if that
# is found to be useful. However note the functions that return project relative
# paths further below.

read -r -d '' script_adp_string <<-"EOF"
  local bash_source
  if [[ -n "${BASH_SOURCE[1]}" ]]; then
    bash_source="${BASH_SOURCE[1]}"
  elif [[ -n "${BASH_SOURCE[0]}" ]]; then
    bash_source="${BASH_SOURCE[0]}"
  else
    echo 'Error: Unable to determine script path in script_adp.' >&2
    return 1
  fi
  #echo
  #echo bash_source: $bash_source
  local absolute_script_dp
  absolute_script_dp=$(dirname "$(realpath "$bash_source" 2>/dev/null)")
  if [[ $? -ne 0 ]]; then
    echo 'Error: Failed to resolve path in script_adp.' >&2
    return 1
  fi
  echo "$absolute_script_dp"
EOF
script_adp(){
  eval "$script_adp_string"
}



# Exports, and give the exported environment a name
#

  export script_adp_string 
  export -f script_adp
#  export -f script_adp script_fn script_dp script_fp workspace
#  export ENV=$(script_fp)
#  echo ENV "$ENV"
  
