#!/usr/bin/env bash

# Removes all files found in the build directories. It asks no questions as to
# how or why the files got there. Be especially careful with the 'shell' directory
# if you added scripts to it for release with the project they will be deleted.
# consider adding a `shell-leaf` directory instead of adding scripts to `shell`.

# input guards
  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# remove files
  set -x
  cd "$REPO_HOME"/developer
  rm -r scratchpad/*
  rm jvm/*
  rm shell/*
  set +x

echo "$(script_fn) done."

