#!/usr/bin/env bash
# remove  all files created by make's call to `javac`

# input guards
  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# remove files
  set -x
  cd "$REPO_HOME"/developer
  rm -r scratchpad/com/ReasoningTechnology/"$PROJECT"
  set +x

echo "$(script_fn) done."
