#!/usr/bin/env bash
# remove all files made by `make`

# input guards

  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# wrappers to clean (this list space separated list will grow)

  wrapper=$(shell_wrapper_list)

# remove files

  set -x
  cd "$REPO_HOME"/developer
  rm -r scratchpad/com/ReasoningTechnology/"$PROJECT"
  rm jvm/"$PROJECT".jar
  rm shell/{$wrapper}
  set +x

echo "$(script_fn) done."
