#!/usr/bin/env bash
# remove files made by `make` and by `release`

# input guards

  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# things to clean

  release_dir="$REPO_HOME"/release
  wrapper=$(shell_wrapper_list)

# remove files
  set -x
  cd "$REPO_HOME"/developer
  rm -r scratchpad/com/ReasoningTechnology/"$PROJECT"
  rm jvm/"$PROJECT".jar
  rm shell/{$wrapper}
  rm -f "$release_dir"/"$PROJECT".jar
  rm -f "$release_dir"/{$wrapper}
  set +x

echo "$(script_fn) done."

