#!/bin/env bash

# input guards

  env_must_be="developer/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer

echo "Compiling files..."
  set -x
  javac -d scratch_pad javac/*.java
  set +x
  if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
  fi

echo "Creating JAR file..."
  set -x
  jar_file=jvm/"$PROJECT".jar
  mkdir -p jvm
  jar cf $jar_file -C scratch_pad .
  set +x
  if [ $? -eq 0 ]; then
    echo "JAR file created successfully: $jar_file"
  else
    echo "Failed to create JAR file."
    exit 1
  fi

echo "Creating shell wrappers..."
  mkdir -p shell
  # wrapper is a space separated list
  wrapper=Mosaic
  for file in $wrapper;do
    cat > shell/$file << EOL
#!/bin/bash
java com.ReasoningTechnology."$PROJECT".$file
EOL
    chmod +x shell/$file
  done

echo "$(script_fp) done."

