#!/usr/bin/env bash

# Caveat: the 'shell' directory is for built wrapper
# functions. `clean_build_directories` will remove all the files in this
# directory. For bespoke scripts used by the tester, put them in the `tool`
# directory.

# input guards
  env_must_be="tester/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# remove files
  set -x
  cd "$REPO_HOME"/tester
  rm -r scratch_pad/*
  rm jvm/*
  rm shell/*
  set +x

echo "$(script_fn) done."
