#!/bin/env bash

# input guards

  env_must_be="tester/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

echo "Compiling files..."

  set -x
  cd $REPO_HOME/tester
  javac -d scratch_pad javac/*.java
  jar cf jvm/TestBench"$PROJECT".jar -C scratch_pad .
  set +x 

echo "Creating shell wrappers..."
  mkdir -p shell
  # wrapper is a space separated list
  wrapper=TestTestBench
  for file in $wrapper;do
    cat > shell/$file << EOL
#!/bin/env bash
java com.ReasoningTechnology."$PROJECT".Test.$file
EOL
    chmod +x shell/$file
  done

echo "$(script_fp) done."
